export const enum ROLES {
  TENANT_ADMIN_MASTER = "TENANT_ADMIN_MASTER",
  ADMIN_USER = "ADMIN_USER",
  CUSTOMER_USER = "CUSTOMER_USER",
  WAITER_USER = "WAITER_USER",
  CHEF_USER = "CHEF_USER",
  RESTAURANT_CASHIER_USER = "RESTAURANT_CASHIER_USER",
}
